### ISSUE TITLE
Finalize architecture for automated build script artifacts

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/LevelTemplate#14]
I'm happy with the results of the experiments here so far with capturing artifacts from the automated build script.

For the LevelTemplate, I would be okay with just capturing release and debug artifacts when pushes are made.

If we want a formal release and changelog, then I think we should explore forcing the automated build script to line up with the tagged version of the release from the repository. Otherwise, this feature could be not provided in LevelTemplate and we just use the appveyor generated build number until a future date.

Discussion about packaging the readme should probably be ignored here and considered for other projects with planned binary releases.

So, I think I'm proposing we rollback the automated pull of binary dlls from this project and just apply it to other projects. We can leave the token generation in place for Linux/Wine users to experiment with.

**Comment by DanRStevens** [comment]
I agree we should take out the changes to attach binary release packages for this project.

We probably do still want automated GitHub releases on tags of the master branch. There would be no artifacts to upload though. It would merely consist of the source code packages which GitHub automatically provides. Whether or not we end up using this is another question.

The build artifacts could still be packaged and stored on the CI servers. I guess that's kind of optional. I believe I can update the release package names for the tagged builds, and fall back to AppVeyor build number names for non-tagged builds.

Perhaps the release package uploading can be commented out, with an explanation given. That way it can still serve as an example for other projects.

**Comment by DanRStevens** [comment]
Ok, so after experimenting with this, I think I've solved many of the general concerns we had, though I was not able to turn off uploading of artifacts for a release. As GitHub provides ZIP files of the source for tagged versions anyway, it's questionable if creating a formal release with no binary artifacts is of much value. I suppose you might get a release description, but we're currently leaving the description blank, so again, no real value.

I think what I'll do is move the generalized release code I was working on over to the op2ext project, which has an open PR for auto release tagging. This project can have the auto release tag section removed, since it doesn't seem to really apply to this project in any meaningful way.

**Comment by Brett208** [comment]
Sounds like a good plan I guess we may just close this issue soon.

**Comment by DanRStevens** [comment]
Oh, you know why we need this here? Because the cloned/forked projects which become actual levels will need that stuff setup. Hence it should be part of the template. Just maybe disabled or commented out or something.

Or perhaps just not used? I suppose it doesn't hurt if we just don't create any tags/releases.
